### ISSUE TITLE
Link to pretrained networks broken

### ISSUE THREAD

**Issue by cheripai** [huanglianghua/siamfc-pytorch#1]
It seems that the primary source to the pretrained networks is unavailable (https://bit.ly/cfnet_networks)
If you have the weights, could you please upload them elsewhere?

Thanks!

**Comment by cheripai** [comment]
I found a link to the weights here under pre-trained networks: http://www.robots.ox.ac.uk/~luca/cfnet.html

**Comment by huanglianghua** [comment]
@cheripai Thanks for pointing this out. The link of pre-trained networks has been updated.
