### ISSUE TITLE
验证损失问题

### ISSUE THREAD

**Issue by noUmbrella** [huanglianghua/siamfc-pytorch#10]
请问有没有遇到过验证损失一开始减小后来越来越大的问题？

**Comment by huanglianghua** [comment]
@noUmbrella SiamFC 训练过程验证集精度会有很大的抖动，OTB上AUC抖动也在3~5个点左右。越来越大没有遇到过。

**Comment by AdrienGuo** [comment]
我也遇到相似的問題，驗證的 loss 幾乎沒有下降，我是用 GOT-10K 當作資料集。

下圖的實線是訓練的 loss，虛線是驗證的 loss。
<img width="449" alt="Screen Shot 2022-12-27 at 15 08 28" src="https://user-images.githubusercontent.com/50326960/209626446-4654442b-c980-43e8-8dd4-8d09ee5f5ac6.png">

不過奇怪的是，儘管驗證的 loss 沒有下降，但第50個epoch的model 很明顯比第 1 個還要好很多，有人可以解釋這種現象嗎？
