### ISSUE TITLE
关于数据预处理的疑问

### ISSUE THREAD

**Issue by liminn** [huanglianghua/siamfc-pytorch#12]
您好，感谢您提供的GOT数据集！我有一些疑问，想请教一下。
在`pairwise.py`文件中存在如下代码：
```Python
class Pairwise(Dataset):

    def __init__(self, seq_dataset, **kargs):
        super(Pairwise, self).__init__()
        self.cfg = self.parse_args(**kargs)

        self.seq_dataset = seq_dataset
        self.indices = np.random.permutation(len(seq_dataset))
        # augmentation for exemplar and instance images
        self.transform_z = Compose([
            RandomStretch(max_stretch=0.05),
            CenterCrop(self.cfg.instance_sz - 8),
            RandomCrop(self.cfg.instance_sz - 2 * 8),
            CenterCrop(self.cfg.exemplar_sz),
            ToTensor()])
        self.transform_x = Compose([
            RandomStretch(max_stretch=0.05),
            CenterCrop(self.cfg.instance_sz - 8),
            RandomCrop(self.cfg.instance_sz - 2 * 8),
            ToTensor()])
```
疑问：
-  `CenterCrop(self.cfg.instance_sz - 8)`和`RandomCrop(self.cfg.instance_sz - 2 * 8)`所代表的含义是什么？
- 对于`transform_z`，为什么需要` CenterCrop(self.cfg.instance_sz - 8)`以及`RandomCrop(self.cfg.instance_sz - 2 * 8)`?
- 对于`transform_x`，为什么最终不需要` CenterCrop(self.cfg.instance_sz )`？

我的理解：
- 对于`transform_z `是不是应该只保留`CenterCrop(self.cfg.exemplar_sz)`？
- 对于`transform_x `是不是应该只保留`CenterCrop(self.cfg.instance_sz)`？
- 这样的话，得到的`z`和`x`，才能最准确的和`label`相对应?

**Comment by huanglianghua** [comment]
@liminn 你好，如果只用 CenterCrop，数据固定，模型很容易过拟合，泛化到测试集效果会差。transforms 对 exemplar 和 instance 图像做一些随机处理，降低过拟合。

RandomCrop 随机从图像上抠出一块小于图像大小的区域。另外，label 不完全准确对应反而会让训练的模型更鲁棒，因为对小偏移也会有较好的响应。

**Comment by liminn** [comment]
@huanglianghua 理解了，谢谢！ 还有最后一个疑问：对于`transform_x`，为什么最终不需要再加上`CenterCrop(self.cfg.instance_sz )`，以保证search image的尺寸为255x255？

**Comment by huanglianghua** [comment]
@liminn SiamFC 是全卷积网络，search image 的大小不需要固定，只要保证输出和 label map 大小一致就行。

代码里训练阶段 search image 在 transform_x 之后是 239x239，测试阶段是 255x255。这些数相差 8 (total_stride) 的倍数都可以 work，根据需要的 search region 大小调整。

**Comment by liminn** [comment]
@huanglianghua 理解了，谢谢！
