### ISSUE TITLE
GPU version of the SiamFC

### ISSUE THREAD

**Issue by leeyeehoo** [huanglianghua/siamfc-pytorch#2]
Hi,

I found out that all the model was conducted under cpu version.

**Comment by HuaijiaLin** [comment]
Just add '.cuda()' for siameseNet works.

**Comment by huanglianghua** [comment]
@leeyeehoo The GPU version as well as the training code of SiamFC (and also other trackers) are included in my new repo [open-vot](https://github.com/huanglianghua/open-vot.git). Thanks.

**Comment by leeyeehoo** [comment]
Thanks, I've also duplicated the result with my own training tracker. Thanks
