### ISSUE TITLE
Question about running speed

### ISSUE THREAD

**Issue by zxb-caffe** [huanglianghua/siamfc-pytorch#23]
Hello
        The original author gave a running speed of 86fps (GPU, search factor of 3). I ran your code at 4fps (cpu, VOT15),
       Is the gap so big?

**Comment by huanglianghua** [comment]
Yes. SiamFC on CPU is far from real-time. The fast speed (86 fps) is reported on GPUs. For CPU usage, you may want other trackers such as ECO-HC, BACF, KCF, etc.
