### ISSUE TITLE
question about how to prepare dataset

### ISSUE THREAD

**Issue by Jee-King** [huanglianghua/siamfc-pytorch#26]
Hi, I'm a newer in tracking. So, how to prepare training datasets? just download and put it in _./data_?

**Comment by incredible-john** [comment]
Hi, did you figure out how to prepare the dataset yet? I have the same question as yours.

**Comment by incredible-john** [comment]
> Hi, I'm a newer in tracking. So, how to prepare training datasets? just download and put it in _./data_?

Hi, did you figure out how to prepare the dataset yet? I have the same question as yours.
