### ISSUE TITLE
install opencv

### ISSUE THREAD

**Issue by laisimiao** [huanglianghua/siamfc-pytorch#28]
in README.md: intall OpenCV using menpo channel, can i just install without add any -c parameter? it must install by menpo channel?

**Comment by huanglianghua** [comment]
The repo works for any OpenCV version.

However, I developed the algorithm using the `menpo` channel, and I found it more reliable since the read image gives exactly the same pixel values as `PIL.Image.open` (not same for many other OpenCV versions). So a `menpo` channel is more recommended.
