### ISSUE TITLE
Minor bug in crops.py?

### ISSUE THREAD

**Issue by YugeTen** [huanglianghua/siamfc-pytorch#3]
Hi,

I might be completely wrong about this but in line 12-13 in crops.py it reads:

>     xright_pad = max(0, int(round(pos_x + c)) - frame_sz[1])
>     ybottom_pad = max(0, int(round(pos_y + c)) - frame_sz[0])

From my understanding, the first variable is checking if the crop exceeds the right-hand side limit of the frame (x direction) and second one for bottom (y direction), so shouldn't it instead be:

>     xright_pad = max(0, int(round(pos_x + c)) - frame_sz[0])
>     ybottom_pad = max(0, int(round(pos_y + c)) - frame_sz[1])

**Comment by huanglianghua** [comment]
@YugeTen the code is updated and this part has been fixed. Thanks.
