### ISSUE TITLE
question about run demo.py 

### ISSUE THREAD

**Issue by yuwenyouhaoran** [huanglianghua/siamfc-pytorch#33]
when i run demo.py
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    from siamfc import TrackerSiamFC
ModuleNotFoundError: No module named 'siamfc'

**Comment by huanglianghua** [comment]
Hi, you can copy `demo.py` to the root directory (`cp tools/demo.py .`) and run `python demo.py`.

**Comment by HaoranWy** [comment]
thank you
