### ISSUE TITLE
the got-10k dataset can not be downloaded

### ISSUE THREAD

**Issue by lewisli66** [huanglianghua/siamfc-pytorch#34]
when I dowanload the got-10k dataset in http://got-10k.aitestunion.com/downloads.It shows the error that 500 Internal Server Error.So I can not download this dataset. can you help me solve this problem?thank you！

**Comment by huanglianghua** [comment]
Hi, do you mean [http://got-10k.aitestunion.com/downloads](http://got-10k.aitestunion.com/downloads)? This link works for me. Please let me know if there is still any problem when downloading.

**Comment by lewisli66** [comment]
http://got-10k.aitestunion.com/downloads is ok now.thank you for your reply.
