### ISSUE TITLE
about the results

### ISSUE THREAD

**Issue by Cris-zj** [huanglianghua/siamfc-pytorch#4]
Thank you for the job! I have got the results, can you show the results on you machine? We want to compare them. Thank you for your reply.

**Comment by huanglianghua** [comment]
@Cris-zj The results on 7 datasets are no available. Thanks.

**Comment by dkgupta90** [comment]
> Thank you for the job! I have got the results, can you show the results on you machine? We want to compare them. Thank you for your reply.

Hi @Cris-zj : Did your results match with the results provided for the 7 datasets? I am getting quite some difference in OTB13 and UAV123. I have not yet tested on others.
