### ISSUE TITLE
Why is this port of SiamFC so slow? I get about 10fps with 1080Ti but author of the original paper claims 50-100 fps?

### ISSUE THREAD

**Issue by yxchng** [huanglianghua/siamfc-pytorch#5]

**Comment by huanglianghua** [comment]
The image reading, resizing, padding, cropping, etc. of PIL.Image is very slow. These operations run on CPU. You can try on cv2 for speeding up. The cv2 is much faster, but is less accurate and it acts differently on different machines.

**Comment by yxchng** [comment]
@huanglianghua Do you have examples of how cv2 is less accurate and acts differently on different machines? I have been using cv2 for years and it works great!

**Comment by huanglianghua** [comment]
@yxchng The decoding of OpenCV is based on libjpeg. [Here](https://github.com/skvark/opencv-python/issues/65) is a discussion on OpenCV with different versions/platforms producing different results.

It might not be a problem for other CV applications. But for tracking, the performance is very vulnerable to small changes, as is also indicated in the summary on [zhihu](https://zhuanlan.zhihu.com/p/34222060?utm_source=weibo&utm_medium=social) at the end of the article.

**Comment by melodyhappy** [comment]
the result on my computer is only 1FPS. And I found my GPU was not working at all.Do you know how to solve this problem?   Thx

**Comment by huanglianghua** [comment]
@melodyhappy You can check my new commit, where all image operations (except for reading) are implemented in cv2, which is much faster.
