### ISSUE TITLE
hello,Dr.huang,can you share the "pretrained/siamfc_new" file in run_training.py

### ISSUE THREAD

**Issue by ZihaoZhao** [huanglianghua/siamfc-pytorch#6]
I want to use your initial weight to train the net.

Hope you share the BaiduYun link.

Thank you very much!

**Comment by huanglianghua** [comment]
Hi @ZihaoZhao, the SiamFC is trained from scratch with randomly initialized net weights (the same setting as in original paper), and there is no pretrained initial weight file.

You can execute `run_training.py` for training the net, where no initial weights are required.

**Comment by huanglianghua** [comment]
Hi Zihao,

The SiamFC is trained from scratch using randomly initialized weights, and there are no pretrained initial weights for the net. You can exrcute run_training.py for training the net, where no initial weight file is required.

Best,
Lianghua

发自我的 iPhone
