### ISSUE TITLE
can you share any user friendly web download link of dataset, google drive best

### ISSUE THREAD

**Issue by gjpicker** [huanglianghua/siamfc-pytorch#7]
Hi Mr Huang 
Very thanks for the marvel and light reproduce work in pytorch ,a good job.
 
And a bit suggestion , could you share some dataset's download link by google drive ?  However, the office download link was too slow to irk myself .    

Can you fill in miss blank by  google_drive_link by manual ?

| Dataset       | Google Drive    | Baidu cloud | office download page or link  |
|:-----------   |:----------------:|:----------------:| ---:|
| GOT-10k |  copyright/ private link  | copyright/private link         | [obtain](http://got-10k.aitestunion.com/downloads)             |<--------------------------------------------------------------|----------------------------------|------------------------------------|--------------------->
|DukeMTMC-VideoReID  | [link](https://drive.google.com/open?id=1qIadJTpY3Wpvsubui2c4jIQTUhAWA1-y)  |optional |[office](http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-VideoReID.zip) |<--------------------------------|----------------------------------|------------------------------------|--------------->
| DukeMTMC-reID | [link](https://drive.google.com/uc?export=download&id=1jjE85dRCMOgRtvJ5RQV9-Afs-2_5dY3O) / [ref](https://github.com/layumi/DukeMTMC-reID_evaluation#download-dataset) | optional | [office](http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-reID.zip)| 
|dukemtmc i don't known |  [link](https://drive.google.com/uc?id=0B0VOCNYh8HeRdnBPa2ZWaVBYSVk)  / [ref](https://github.com/Cysu/open-reid/blob/master/reid/datasets/dukemtmc.py)  | optional | [github_open_reid](https://github.com/Cysu/open-reid)  | 
|OTB (2013/2015) | miss | optional | [office](http://cvlab.hanyang.ac.kr/tracker_benchmark/index.html)  | 
|VOT (2018)| miss | optional | [office](http://votchallenge.net)  | 
|DTB70| [box](https://www.dropbox.com/s/s1fj99s2six4lrs/DTB70.tar.gz?dl=0) | [pan](https://pan.baidu.com/s/1SftGHD7SyIFyBXExHbbYAQ) | [office](https://github.com/flyers/drone-tracking)  | 
|TColor128| miss | optional | [office](http://www.dabi.temple.edu/~hbling/data/TColor-128/TColor-128.html)  | 
|NfS| goto_office | goto_office | [office](http://ci2cv.net/nfs/index.html)  | 
|UAV123| [link](https://drive.google.com/file/d/0B6sQMCU1i4NbNGxWQzRVak5yLWs/edit) / [ref](https://ivul.kaust.edu.sa/Pages/Dataset-UAV123.aspx) | optional | [office](https://ivul.kaust.edu.sa/Pages/pub-benchmark-simulator-uav.aspx)  | 
|ILSVRC2017_VID | miss |optional |  [office](http://image-net.org/challenges/LSVRC/2017/) |
|ILSVRC2015_VID | miss |optional |  [office](http://bvisionweb1.cs.unc.edu/ilsvrc2015/ILSVRC2015_VID.tar.gz) |
|Dataset-NUS-PRO| miss | [link](https://pan.baidu.com/s/1pJHvbSn) / [ref](http://www.zhuanzhi.ai/knowledge/013c97b493dada87bd9074b73bef198e) | [office](http://faculty.ucmerced.edu/mhyang/papers/pami15_nus_pro.pdf) |

**Comment by huanglianghua** [comment]
Hi @gjpicker, sorry for replying so late, I was quite busy on some works. Thanks for your suggestion, but I do not have the google drive links for the datasets, although I agree that offering the unified links would be helpful.
